name: CD
on:
  push:
    branches:
      - main
jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run ESLinter
        run: npm run lint

      - name: Run Prettier
        run: npm run prettier

      - name: Run Tests
        run: npm run test
  Build:
    name: Build
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        env:
          SPACE: ${{ secrets.SPACE}}
          ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
        run: npm run build
  Deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: |
          touch .env.local
          echo SPACE=${{ secrets.SPACE }} >> .env.local
          echo ACCESSTOKEN=${{ secrets.ACCESSTOKEN }} >> .env.local
          npm run build
      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
